dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
- curl -T -v lesson_1_app-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uyellowcoffee:$BINTRAY_API_KEY "https://api.bintray.com/content/yellowcoffee/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/lesson_1_app-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
